andante:
  create_driver:
    ros__parameters:
      dev: "/dev/ttyUSB0"
      # baud: 115200
      base_frame: "base_footprint"
      odom_frame: "odom"
      latch_cmd_duration: 1.0
      loop_hz: 30.0
      publish_tf: true
      oi_mode_workaround: true

  v4l2_camera:
    ros__parameters:
      video_device: "/dev/video0"
      pixel_format: "YUYV"
      output_encoding: "rgb8"
      image_size: [640, 480]

  andante_camera_linetrace:
    ros__parameters:
      base_frame: "base_footprint"
      camera:
        use_topic: true
        camera_src: "/dev/video0"
        width: 640
        height: 480
        fps: 30
        mode: "YUYV" # BGR, GRAY, YUYV
        camera_matrix:
          fx: 466.04801626378963
          fy: 466.9085133301153
          cx: 307.0467825072331
          cy: 246.50641184905263
        dist:
          - -0.4224118594449603
          - 0.26723128152672515
          - -0.0006153829745503066
          - 0.0004862571635758298
          - -0.1260595834413847
        # using andante_camera_linetracer/calibration
        M:
          [
            0.11965446720186285,
            -3.4726249707478027,
            -542.0259861827699,
            -1.3089473533294145,
            -3.4333136314150967,
            485.0045092418728,
            0.0009971205600155363,
            -0.06862834874800448,
            1.0,
          ]
      # Occupancy Gridの設定
      map:
        size: 1.0 # [m]
        resolution: 0.01 # [m/pixel]
        trans_tolerance: 0.01
        rotate_tolerance: 0.08726646259
      motion_control:
        center_circle_radius: 0.05 # [m]
        max_linear_vel: 1.0
        min_linear_vel: 0.1
        angular_vel_scale: 3

      calibration:
        src: "img/60_2.jpg"
        # marker_size: 0.093 # [m]
        marker_size: 0.2 # gazebo
        # pose of marker center from robot
        marker_pose:
          x: 0.6 # [m]
          y: 0 # [m]
          theta: 3.14159265359
          # theta: 0
